project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

base_path: '.'
preserve_hierarchy: true

files:
  - source: '/localization_ini/en.ini'
    translation: '/localization_ini/%two_letters_code%.ini'
    scheme: ini
